[package]
name = "blockchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
serde = "1.0"
serde_json = "1.0"
serde-pickle = "1.1.1"
sha2 = "0.10.8"
base64 = "0.21.5"
